language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

env:
  - MONGODB_VERSION=2.2.x
  - MONGODB_VERSION=2.4.x
  - MONGODB_VERSION=2.6.x
  - MONGODB_VERSION=3.0.x
  - MONGODB_VERSION=3.2.0

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
